version: "3.8"

services:
  db:
    image: "postgres:12.2-alpine"
    container_name: "database"
    ports:
      - "5432:5432"
    enviroment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres:/var/lib/postgresgl/data

  web:
    build:
    container_name: "rest-api"
    enviroment:
      DB_UERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_HOST: "db"
      DB_TABLE: "postgres"
      DB_PORT: "5432"
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      fullstack:
        driver: bridge

